services:
  weather-bot:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    
    image: ktrileo/weather-bot:1.9898
    container_name: weatherbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOSTNAME=sheoldred  # Use CONTAINER_NAME as discussed
      - CONTAINER_NAME=sheoldred
    networks:
      - common_network

networks:
  common_network:
    driver: bridge